[Local]
source = maildir://~/.local/share/email/ # Replace with the path to your mbsync mail root
outgoing = /usr/bin/msmtp
from = <email>
folders-sort = Inbox
check-mail = 1m
check-mail-cmd = mbsync -a
check-mail-timeout = 30s
