include rose-pine.conf

# Use nvim for scrollback
scrollback_pager nvim --cmd 'set eventignore=FileType' +'nnoremap q ZQ' +'set nomodified readonly nolist' +'$' -

# Disable bell
enable_audio_bell no

# Background
background_opacity 0.8
dynamic_background_opacity yes
background_blur 32

# Remove trailing spaces when copying
strip_trailing_spaces smart

# Gaps between terminal output and borders
# window_padding_width 6

# Reset font size
map ctrl+shift+0 change_font_size all 0

open_url_with linkhandler
