$terminal = $TERMINAL
$fileManager = nautilus
$menu = rofi -show drun
$screenshot = wayfreeze --hide-cursor --after-freeze-cmd 'grim -g "$(slurp)" - | wl-copy; killall wayfreeze'
$mainMod = SUPER

##################
# Spawn programs #
##################

bind = $mainMod, t, exec, $terminal
bind = $mainMod, e, exec, $fileManager
bind = $mainMod, S, exec, $menu
bind = $mainMod SHIFT, s, exec, $screenshot
bind = $mainMod SHIFT, L, exec, hyprlock
bind = ALT, TAB, workspace, e+1
bind = $mainMod, semicolon, exec, rofimoji

##################
# Quit window/WM #
##################
bind = $mainMod, q, killactive,
bind = $mainMod SHIFT, q, exit,

##################
# Change layouts #
##################
bind = $mainMod, M, fullscreen, 1
bind = $mainMod SHIFT, F, fullscreen, 0
bind = $mainMod, F, togglefloating,

################
# Move columns #
################
# bind = $mainMod, k, layoutmsg, cycleprev
# bind = $mainMod, j, layoutmsg, cyclenext
bind = $mainMod, l, layoutmsg, move +col
bind = $mainMod, h, layoutmsg, move -col

# Split workspaces
# Switch workspaces with mainMod + [0-5]
bind = $mainMod, 1, split-workspace, 1
bind = $mainMod, 2, split-workspace, 2
bind = $mainMod, 3, split-workspace, 3
bind = $mainMod, 4, split-workspace, 4
bind = $mainMod, 5, split-workspace, 5

# Move active window to a workspace with mainMod + SHIFT + [0-5]
bind = $mainMod SHIFT, 1, split-movetoworkspacesilent, 1
bind = $mainMod SHIFT, 2, split-movetoworkspacesilent, 2
bind = $mainMod SHIFT, 3, split-movetoworkspacesilent, 3
bind = $mainMod SHIFT, 4, split-movetoworkspacesilent, 4
bind = $mainMod SHIFT, 5, split-movetoworkspacesilent, 5

bind = $mainMod Shift, COMMA, split-changemonitor, next
bind = $mainMod Shift, PERIOD, split-changemonitor, prev

bind = $mainMod, COMMA, focusmonitor, +1
bind = $mainMod, PERIOD, focusmonitor, -1

# bind = $mainMod, h, resizeactive, -10 0
# bind = $mainMod, l, resizeactive, 10 0


# bind = $mainMod, z, exec, killall -SIGUSR1 waybar
bind = $mainMod, z, exec, ironbar bar bar toggle-visible

# Move/resize windows with mainMod + LMB/RMB and dragging
bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

##########
# Volume #
##########
bindl = , XF86AudioNext, exec, playerctl next
bindl = , XF86AudioPause, exec, playerctl play-pause
bindl = , XF86AudioPlay, exec, playerctl play-pause
bindl = , XF86AudioPrev, exec, playerctl previous
bindel = ,XF86AudioRaiseVolume, exec, wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 5%+
bindel = ,XF86AudioLowerVolume, exec, wpctl set-volume @DEFAULT_AUDIO_SINK@ 5%-
bindel = ,XF86AudioMute, exec, wpctl set-mute @DEFAULT_AUDIO_SINK@ toggle
bindel = ,XF86AudioMicMute, exec, wpctl set-mute @DEFAULT_AUDIO_SOURCE@ toggle

##############
# Brightness #
##############
bindel = ,XF86MonBrightnessUp, exec, brightnessctl -e4 -n2 set 5%+
bindel = ,XF86MonBrightnessDown, exec, brightnessctl -e4 -n2 set 5%-

