#############
### INPUT ###
#############

input {
    follow_mouse = 2
    accel_profile = "flat"
    force_no_accel = true

    touchpad {
        natural_scroll = true
        disable_while_typing = false
        middle_button_emulation = true
    }
}

gesture = 3, horizontal, workspace,

